server:
    port: 8080
    servlet:
        context-path: /bitespeed
### Used for developement purpose        
spring.jpa.hibernate.ddl-auto: none
spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
spring.datasource.url: jdbc:mysql://localhost:3306/bitespeed?autoReconnect=true&allowPublicKeyRetrieval=true&useSSl=false
spring.datasource.username: root
spring.datasource.password: Root@1212
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: false

### Used for docker container
#spring.jpa.hibernate.ddl-auto: create
#spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
#spring.datasource.url: jdbc:mysql://db:3306/bitespeed?autoReconnect=true&allowPublicKeyRetrieval=true&useSSl=false
#spring.datasource.username: admin
#spring.datasource.password: Root@1212
#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: false